Migrated template to latex only
RPGLibrarium/Multiversum pull request #7
Opened 2019-12-08 14:30 UTC by Paradyx

2019-12-09 18:24 UTC, sudo42 requested changes
- no table of contents is embedded in the resulting document
- the text "Ausgabe Nr. XX" is misaligned (this might be caused by a missing release date … but is not nice nevertheless)
- the resulting release files are written to the project\s root dir, instead of `ausgaben`
- I would suggest using a directory `tex` (or similar) for LaTeX source files

**otherwise/overall:** looks good, besides minor itches  
**but:** I personally dislike `Makefile`s … just a personal preference, no reason for rejection

2019-12-09 21:49 UTC, Paradyx commented
The template is not meant to be used without the variables. So second point is not an issue.

2019-12-09 22:34 UTC, Paradyx commented
All others should be fixed

2019-12-12 16:06 UTC, sudo42 approved these changes

2019-12-12 16:06 UTC, merged